# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-22 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
    ]
