# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20190322_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Role'),
        ),
    ]
