# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20190322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sign',
            name='temperature',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sign',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
