# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20190322_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
