# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-23 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20190323_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
    ]
