# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20190323_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Teacher'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Account'),
        ),
    ]
