# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20190325_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manager_class_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
