# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_teacher_manager_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img_a',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
