# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_student_img_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
