# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-10 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_sign_sign_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='hand_img',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='sign',
            name='mouth_img',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
